# Generated by Django 3.2.23 on 2024-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
